version: '3.7'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - ${MEDIA_MONGODB_PORT}:27017
    command: mongod --replSet rs0 --bind_ip_all

  mongosetup:
    image: mongo:latest
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      MEDIA_MONGODB_INIT_SLEEP: ${MEDIA_MONGODB_INIT_SLEEP}
    entrypoint: |
      bash -c "sleep ${MEDIA_MONGODB_INIT_SLEEP} && mongosh --host mongodb --eval 'rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"localhost:27017\" }]});'"
    restart: "no"
